SELECT
	SKU.NAME,
	SUM(
		CASE
			WHEN EXTRACT(
				MONTH
				FROM
					SALES.TRANSACTION_DATE
			) IN (EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months'), EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months')) THEN SALES.PRIMARY_SALES
			ELSE 0
		END
	) AS TOTAL_SALES_OCT_NOV,
	SUM(
		CASE
			WHEN EXTRACT(
				MONTH
				FROM
					SALES.TRANSACTION_DATE
			) IN (EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months'), EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months')) THEN TARGET.TARGET_VALUE
			ELSE 0
		END
	) AS TOTAL_TARGET_OCT_NOV,
	ROUND(
		(
			SUM(
				CASE
					WHEN EXTRACT(
						MONTH
						FROM
							SALES.TRANSACTION_DATE
					) IN (EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months'), EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months')) THEN SALES.PRIMARY_SALES
					ELSE 0
				END
			) / NULLIF(
				SUM(
					CASE
						WHEN EXTRACT(
							MONTH
							FROM
								SALES.TRANSACTION_DATE
						) IN (EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months'), EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months')) THEN TARGET.TARGET_VALUE
						ELSE 0
					END
				),
				0
			)
		) * 100,
		2
	) AS ACHIEVEMENT_PERCENTAGE,
	SUM(
		CASE
			WHEN EXTRACT(
				MONTH
				FROM
					SALES.TRANSACTION_DATE
			) IN (EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months'), EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months')) THEN SALES.PRIMARY_SALES - TARGET.TARGET_VALUE
			ELSE 0
		END
	) AS DEFICIT_OR_SURPLUS_OCT_NOV,
	TARGET.TARGET_VALUE AS DECEMBER_TARGET
FROM
	SALES
	JOIN HQ ON SALES.HQID = HQ.ID
	JOIN TARGET ON HQ.ID = TARGET.HQID
	AND SALES.SKUCODE = TARGET.SKUCODE
	JOIN SKU ON SALES.SKUCODE = SKU.CODE
WHERE
	EXTRACT(
		MONTH
		FROM
			SALES.TRANSACTION_DATE
	) IN (EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months'), EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months'))
	AND EXTRACT(
		MONTH
		FROM
			TARGET.TARGET_DATE
	) = EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '1 months')
GROUP BY
	SKU.NAME,
	TARGET.TARGET_VALUE
HAVING
	SUM(
		CASE
			WHEN EXTRACT(
				MONTH
				FROM
					SALES.TRANSACTION_DATE
			) IN (EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months'), EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months')) THEN SALES.PRIMARY_SALES - TARGET.TARGET_VALUE
			ELSE 0
		END
	) <> 0
ORDER BY
	DEFICIT_OR_SURPLUS_OCT_NOV DESC;